# Generated by Django 5.0.3 on 2024-07-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descr',
            new_name='description',
        ),
    ]
