# Generated by Django 5.0.3 on 2024-07-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Password',
            new_name='password',
        ),
    ]
